### ISSUE TITLE
Sanitize YouTube links

### ISSUE THREAD

**Issue by Lurk** [Lurk/clink#101]
![image](https://github.com/Lurk/clink/assets/426748/6329cf63-c0a0-404c-9fd4-6f19d3ff48e0)

Credit: 
https://anticapitalist.party/@kropot/111099960211372703

**Comment by Lurk** [comment]
Looks like Spotify has the same tracking

**Comment by 0x61nas** [comment]
The reason that makes us can't write a pattern for it in the `exit` array is the changeable video ID, right?

**Comment by Lurk** [comment]
@0x61nas no. Exit vec is for unwrapping exit URLs. 

For example: `https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjMuu2zrreBAxUt2gIHHaDVC_gQyCl6BAgqEAM&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ&usg=AOvVaw0aHtehaphMhOCAkCydRLZU&opi=89978449`

Will be unwrapped to: `https://www.youtube.com/watch?v=dQw4w9WgXcQ`

What we want to achieve in this issue is that the 'remove' mode will remove the `si` query param but only if the host is `youtube.com`.  I am not sure that we can just add `si` to `ClinkConfig.params` because maybe, in some cases (not YouTube), it is legitimate query param.
