### ISSUE TITLE
Systemd service file

### ISSUE THREAD

**Issue by murlakatamenka** [Lurk/clink#5]
I think it's more about packaging, but a simple systemd service file would accompany `clink` nicely

Sample `~/.config/systemd/user/clink.service` I got for myself:

```ini
[Unit]
Description=Clink - cleans links in clipboard from utm_<shit>

[Service]
ExecStart=/usr/bin/clink

[Install]
WantedBy=multi-user.target
```

```sh
sudo systemctl daemon-reload
systemctl --user enable --now clink.service
```
and `clink` will do the job by itself, no maintenance needed.

**Comment by Lurk** [comment]
I am still figuring out the best way to package releases for different platforms. 
I definitely will add a service file to releases for *nix systems.
