### ISSUE TITLE
Clean redirection URLs

### ISSUE THREAD

**Issue by Freso** [Lurk/clink#93]
Not sure if this would be too much feature creep, but the thing I was looking for when I came across this was something that would clean up redirection URLs. Some of the redirection pages I found in MusicBrainz’s database was documented in a bot/script I wrote to clean those up ([actual code to clean up the URL in the `get_target_url()` function](https://github.com/Freso/musicbrainz-bot/blob/82e37124cdea83f639d133136809fcb898a3ff2b/exit_url_cleanup.py#L55-L80)):

https://github.com/Freso/musicbrainz-bot/blob/82e37124cdea83f639d133136809fcb898a3ff2b/exit_url_cleanup.py#L19-L38

This could be a really neat check to add prior to removing query parameters from the URLs to further reduce the amount of tracking done.

**Comment by Lurk** [comment]
@Freso can you please check the latest release?

**Comment by Freso** [comment]
Thanks! :)
